set nocompatible
filetype off

runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

filetype plugin indent on
syntax on

augroup myvimrc
  autocmd!
  autocmd BufWritePost $MYVIMRC source $MYVIMRC
  autocmd BufWritePost $MYVIMRC AirlineRefresh
  autocmd BufWritePost $MYVIMRC AirlineRefresh
augroup END

" Color scheme setup
let g:solarized_termtrans=1
set t_Co=16
set background=light
colorscheme solarized

" Powerline configuration
set laststatus=2
set noshowmode
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

" GViM
if has("gui_running")
  if has("gui_macvim")
    set guifont=Source\ Code\ Pro\:h18
  endif
endif

set number
set nowrap
set encoding=utf-8
set wildignore +=node_modules,coverage,cache,tmp,vendor,*.png,*.jpg

" Disable opening message
set shortmess+=I

set ignorecase
set smartcase

set backspace=indent,eol,start
set expandtab
set shiftwidth=2
set softtabstop=2
set smarttab
set smartindent

set foldmethod=syntax
set foldlevel=1
set foldlevelstart=1

" Stops ESC delay
set ttimeoutlen=10

" Allow mouse usage
set mouse=a

" Clear whitespace at the end of lines automatically
autocmd BufWritePre * :%s/\s\+$//e

" Don't fold anything.
autocmd BufWinEnter * set foldlevel=999999

" Set filetype for ruby config files
autocmd BufNewFile,BufRead Podfile,*.podspec,Berksfile,Cheffile,Vagrantfile set filetype=ruby

let g:netrw_liststyle = 3
let g:netrw_preview = 1

let g:jsx_ext_required = 0

autocmd Filetype javascript setlocal ts=2 sts=2 sw=2 expandtab

set noswapfile

let g:ctrlp_show_hidden = 1

set clipboard=unnamed
