" Install Vundle.vim
if !isdirectory(expand('~/.vim/bundle/Vundle.vim'))
  silent !git clone https://github.com/gmarik/Vundle.vim ~/.vim/bundle/Vundle.vim
endif

" Setup Vundle.vim
if !isdirectory(expand('~/.vim/bundle/Vundle.vim'))
  echoerr "Vundle.vim not installed"
else
  filetype off
  set runtimepath+=~/.vim/bundle/Vundle.vim
  call vundle#begin()

  Plugin 'gmarik/Vundle.vim'
  Plugin 'altercation/vim-colors-solarized'
  Plugin 'bling/vim-airline'
  Plugin 'gorodinskiy/vim-coloresque'
  Plugin 'tpope/vim-fugitive'
  Plugin 'airblade/vim-gitgutter'
  Plugin 'tpope/vim-surround'
  Plugin 'tpope/vim-sleuth'
  Plugin 'tpope/vim-markdown'
  Plugin 'pangloss/vim-javascript'
  Plugin 'mxw/vim-jsx'
  Plugin 'scrooloose/syntastic'
  Plugin 'kien/ctrlp.vim'

  call vundle#end()
endif

filetype plugin indent on

" Install plugins
augroup plugins
  autocmd!
  autocmd VimEnter * PluginInstall
  autocmd VimEnter * bdelete
augroup END

augroup myvimrc
  autocmd!
  autocmd BufWritePost $MYVIMRC source $MYVIMRC
  autocmd BufWritePost $MYVIMRC PluginInstall
  autocmd BufWritePost $MYVIMRC bdelete
  autocmd BufWritePost $MYVIMRC AirlineRefresh
  autocmd BufWritePost $MYVIMRC AirlineRefresh
augroup END

syntax on

" Color scheme setup
let g:solarized_termtrans=1
set t_Co=16
set background=light
colorscheme solarized

" Powerline configuration
set laststatus=2
set noshowmode
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

" Load Go plugins
set rtp+=$GOROOT/misc/vim

set number
set nowrap
set encoding=utf-8
set wildignore +=node_modules,coverage,cache,tmp,vendor,*.png,*.jpg

" Disable opening message
set shortmess+=I

set ignorecase
set smartcase

set backspace=indent,eol,start
set expandtab
set shiftwidth=2
set softtabstop=2
set smarttab
set smartindent

set foldmethod=syntax
set foldlevel=1
set foldlevelstart=1

" Stops ESC delay
set ttimeoutlen=10

" Allow mouse usage
set mouse=a

" Clear whitespace at the end of lines automatically
autocmd BufWritePre * :%s/\s\+$//e

" Don't fold anything.
autocmd BufWinEnter * set foldlevel=999999

" Set filetype for ruby config files
autocmd BufNewFile,BufRead Podfile,*.podspec,Berksfile,Cheffile,Vagrantfile set filetype=ruby

let g:netrw_liststyle = 3
let g:netrw_preview = 1

let g:jsx_ext_required = 0

autocmd Filetype javascript setlocal ts=2 sts=2 sw=2 expandtab

set noswapfile
